# Conda environment file
# Create a new Conda environment for development with:
# `conda env create -f environment.yml`
# Activate environment:
# `conda activate dokklib`
name: dokklib
dependencies:
  - python=3.8
  - ipython
  - pip
  - pip:
      - pip-tools
      - -rrequirements/requirements.txt
