name: Cloudflare Workers Site CD

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Use Python 3.8
      uses: actions/setup-python@v1.1.1
      with:
        python-version: 3.8
    - name: Install Wrangler
      run: npm install -g @cloudflare/wrangler
    - name: Install Python requirements 
      run: pip install -rrequirements/requirements.txt
    - name: Build site
      run: mkdocs build
    - name: Publish to Worker Sites
      run: wrangler publish
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
